<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use App\Models\Empresa;

class ClienteSeeder extends Seeder
{
    public function run(): void
    {
        $clientes = [
            [
                'empresa_id' => 1,
                'razao_social' => '2P ORGANIZACAO E ASSESSORIA PARA EVENTOS LTDA',
                'cnpj' => '18155359000101',
                'nome_fantasia' => 'VALENTINA PLANEJAMENTO E ORGANIZACAO DE CASAMENTOS',
                'telefone' => '1192890002',
                'email' => 'julianapettinato01@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => '4CS & H DO BRASIL LOCACOES LTDA',
                'cnpj' => '31966010000100',
                'nome_fantasia' => '4cs & H do Brasil Locacoes',
                'telefone' => '2796921146',
                'email' => 'wagner@4cshconcreto.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => '52.258.603 CLEBERSON DOS SANTOS',
                'cnpj' => '52258603000191',
                'nome_fantasia' => null,
                'telefone' => '1177341095',
                'email' => 'alealealealealeale2016@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => '53.069.401 JEFFERSON LUIZ DOS SANTOS RIBEIRO',
                'cnpj' => '53069401000164',
                'nome_fantasia' => null,
                'telefone' => '1186487283',
                'email' => 'jefeseg@outlook.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => '53.311.898 DANIELA SOUZA DE GODOI',
                'cnpj' => '53311898000185',
                'nome_fantasia' => null,
                'telefone' => '1999623202',
                'email' => 'gmcpfinanceiro@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => '54.430.340 ELISANDRO PESSOA DE ALBUQUERQUE',
                'cnpj' => '54430340000181',
                'nome_fantasia' => null,
                'telefone' => '6899206276',
                'email' => 'audebara33@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => '54.942.120 MURILO ALVES DOS SANTOS',
                'cnpj' => '54942120000137',
                'nome_fantasia' => null,
                'telefone' => '1193904440',
                'email' => 'murilo@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => '54.945.586 VITOR SILVA DE OLIVEIRA',
                'cnpj' => '54945586000196',
                'nome_fantasia' => null,
                'telefone' => '1196495111',
                'email' => 'vitor@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => '56.129.629 ROBERTO CARLOS CARDOSO FERREIRA',
                'cnpj' => '56129629000190',
                'nome_fantasia' => null,
                'telefone' => '1188534955',
                'email' => 'robertocarloscardoso005@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => '57.368.010 ANDERSON DA SILVA MARTINS DE SOUSA',
                'cnpj' => '57368010000100',
                'nome_fantasia' => null,
                'telefone' => '1596330983',
                'email' => 'restart.assessoriacontabil@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => '57.452.036 PAULO TINTINO DA SILVA JUNIOR',
                'cnpj' => '57452036000123',
                'nome_fantasia' => null,
                'telefone' => '1125262455',
                'email' => 'jp9837812@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => '58.009.161 JOACI PERALTA NUNES',
                'cnpj' => '58009161000126',
                'nome_fantasia' => null,
                'telefone' => '1173844951',
                'email' => 'joaci.peralta01@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => '58.743.401 TATIANA CRISTINA DE SOUZA',
                'cnpj' => '58743401000111',
                'nome_fantasia' => null,
                'telefone' => '1111806317',
                'email' => 'tcstreinamentos@outlook.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => '59.749.872 THIAGO MIRANDA LOPES',
                'cnpj' => '59749872000108',
                'nome_fantasia' => null,
                'telefone' => '1147991664',
                'email' => 'bombeiroescolta@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => '61.869.733 DAVID TEIXEIRA DO NASCIMENTO',
                'cnpj' => '61869733000151',
                'nome_fantasia' => null,
                'telefone' => '1147481444',
                'email' => 'chokolover2.0@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => '62.005.680 BENSON SAINTILMON',
                'cnpj' => '62005680000193',
                'nome_fantasia' => null,
                'telefone' => '1177192866',
                'email' => 'restartassessoriacontabil@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => '62.019.951 MARCOS VINICIUS ALVES DOS SANTOS',
                'cnpj' => '62019951000160',
                'nome_fantasia' => null,
                'telefone' => '1155322279',
                'email' => 'marcosvinicius15.5@icloud.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => '62.340.224 JEAN JUNIOR ANDRE',
                'cnpj' => '62340224000108',
                'nome_fantasia' => null,
                'telefone' => '6198058774',
                'email' => 'restartassessoriacontabil@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => '62.481.154 CAIO CEZAR DE LIMA',
                'cnpj' => '62481154000108',
                'nome_fantasia' => null,
                'telefone' => '8781290044',
                'email' => '2meiczarempreendedor@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => '62.553.423 SUELI REGINA DOMINGUES LOPES SILVA',
                'cnpj' => '62553423000196',
                'nome_fantasia' => null,
                'telefone' => '1196110262',
                'email' => 'geovaniferreirasilva@hotmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => '62.625.250 DANIEL MENDONCA DE OLIVEIRA',
                'cnpj' => '62625250000174',
                'nome_fantasia' => null,
                'telefone' => '3299448315',
                'email' => 'mendoncadaniel43567@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => '62.697.492 WILLIAM SOUZA COSTA',
                'cnpj' => '62697492000173',
                'nome_fantasia' => null,
                'telefone' => '1599140805',
                'email' => 'restartassessoriacontabil@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => '63.500.402 BRUNO PEREIRA DA SILVA',
                'cnpj' => '63500402000175',
                'nome_fantasia' => null,
                'telefone' => '1164268129',
                'email' => 'brunopereira3393@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => '63.501.216 JUSTINO GONCALVES DA LUZ',
                'cnpj' => '63501216000150',
                'nome_fantasia' => null,
                'telefone' => '1149820528',
                'email' => 'justinogoncalves875@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => '63.505.487 LEONIDAS JOAO DE PAIVA',
                'cnpj' => '63505487000184',
                'nome_fantasia' => null,
                'telefone' => '1157858906',
                'email' => 'leonidasjaodepaiva@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'A L R ELETRICA E CONSTRUCAO LTDA',
                'cnpj' => '41298814000131',
                'nome_fantasia' => null,
                'telefone' => '1896064173',
                'email' => 'edson_assessoria@hotmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'A.C. CONSTRUCOES LTDA',
                'cnpj' => '49161210000150',
                'nome_fantasia' => 'Rocha Construcoes',
                'telefone' => '1176736181',
                'email' => 'anaceliaaraujoconceicao303@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ACADEMIAS GREENLIFE BARRA FUNDA LTDA',
                'cnpj' => '62718073000170',
                'nome_fantasia' => 'Greenlife Barra Funda',
                'telefone' => '8538794067',
                'email' => 'contabilidade@greenlifeacademias.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ACOS GERAIS COMERCIAL LTDA',
                'cnpj' => '10607764000101',
                'nome_fantasia' => null,
                'telefone' => '1933071744',
                'email' => 'nfe@acosgerais.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ACR TEC IMPERMEABILIZACOES S/C LTDA',
                'cnpj' => '03704480000160',
                'nome_fantasia' => null,
                'telefone' => '1138626361',
                'email' => 'acrtecimp@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ADEQUA - SERVICOS DE CONSTRUCAO CIVIL LTDA',
                'cnpj' => '14547417000183',
                'nome_fantasia' => 'ADEQUA CONSTRUCAO',
                'telefone' => '11947543435',
                'email' => 'negocios.fariascontabilidade@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ADILENE SANTOS SOARES',
                'cnpj' => '22360053000156',
                'nome_fantasia' => 'ANJOS DA LIMPEZA TERCEIRIZACOES',
                'telefone' => '1987061504',
                'email' => 'adilene.soares@yahoo.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ADLER TRANSPORTES E LOGISTICA INTEGRADA LTDA.',
                'cnpj' => '33137495000154',
                'nome_fantasia' => null,
                'telefone' => '1120924299',
                'email' => 'contato@adlerlog.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ADRIANA BARBOSA DE OLIVEIRA 38400840836',
                'cnpj' => '26194406000146',
                'nome_fantasia' => 'Ak Estamparia',
                'telefone' => '1123058987',
                'email' => 'akestamparia@outlook.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'AGEIRELLES PRESTACAO DE SERVICOS E ADMINISTRACAO DE CONSTRUCOES EM GERAL LTDA',
                'cnpj' => '59937156000146',
                'nome_fantasia' => 'Ageirelles Servicos de Construcao em Geral',
                'telefone' => '1122818245',
                'email' => 'ace_assessoriacontabil@hotmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'AL CONSTRUCAO CIVIL LTDA',
                'cnpj' => '61262013000123',
                'nome_fantasia' => 'Al Construcao Civil',
                'telefone' => '1599104642',
                'email' => 'denisconstantino1710@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'AL ENGENHARIA LTDA',
                'cnpj' => '47894702000120',
                'nome_fantasia' => 'Al Engenharia Ltda',
                'telefone' => '1591046429',
                'email' => 'restart.assessoriacontabil@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ALAN DAVID MENDES DE ARAUJO',
                'cnpj' => '11297295676',
                'nome_fantasia' => null,
                'telefone' => '11920416924',
                'email' => 'alandavid820@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ALBUQUERQUE ENGENHARIA LTDA',
                'cnpj' => '00361941000150',
                'nome_fantasia' => null,
                'telefone' => '8197900127',
                'email' => 'albuquerqueengenharia@albuquerqueeng.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ALFA MK CONSTRUTORA, ENGENHARIA E ARQUITETURA LTDA',
                'cnpj' => '11231234000166',
                'nome_fantasia' => 'Alfa Mk Construtora',
                'telefone' => '1143387471',
                'email' => 'rm3955@terra.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ALULEV ESCADA LTDA',
                'cnpj' => '73013666000158',
                'nome_fantasia' => 'Alulev',
                'telefone' => '1147873433',
                'email' => 'financeiro@alulev.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ANDERSON DA SILVA CAHE 33817149883',
                'cnpj' => '31201590000144',
                'nome_fantasia' => 'PADRAO TEC',
                'telefone' => '1186175839',
                'email' => 'andersoncahe@hotmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ANDERSON DIEGO MARTINS DE MELO LTDA',
                'cnpj' => '57652785000102',
                'nome_fantasia' => 'J&P MONTAGEM E MANUTENCAO',
                'telefone' => '1596330983',
                'email' => 'restart.assessoriacontabil@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'André de Farias Leandro',
                'cnpj' => '21271963841',
                'nome_fantasia' => null,
                'telefone' => '',
                'email' => 'x@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ANDRE RODRIGUES REGO 00151109230',
                'cnpj' => '31798375000172',
                'nome_fantasia' => 'ARQ&GRAF',
                'telefone' => '1187120994',
                'email' => 'arq2graf@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'Antônia Valdeglace Pereira Paulino',
                'cnpj' => '33467518800',
                'nome_fantasia' => null,
                'telefone' => '',
                'email' => 'duo834149@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ARS INSTALACOES HIDRAULICAS LTDA',
                'cnpj' => '48460520000103',
                'nome_fantasia' => 'Ars Instalacoes Hidraulicas',
                'telefone' => '1598036719',
                'email' => 'restart.assessoriacontabil@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ARTPAVING SPE LTDA',
                'cnpj' => '62684403000154',
                'nome_fantasia' => null,
                'telefone' => '2798222871',
                'email' => 'controladoria@marianaengenharia.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ASAP LOCACAO DE ANDAIMES E EQUIPAMENTOS PARA CONSTRUCAO CIVIL LTDA',
                'cnpj' => '54799917000127',
                'nome_fantasia' => 'Asap Locacao',
                'telefone' => '1197777737',
                'email' => 'cont.delta@terra.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ATELIER AJC SERVICOS DE ACABAMENTO EM GESSO LTDA',
                'cnpj' => '31065959000139',
                'nome_fantasia' => 'ATELIER AJC',
                'telefone' => '1181954566',
                'email' => 'aguinaldocarvalho150@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'BARRETO CONSTRUTORA LTDA',
                'cnpj' => '57904396000119',
                'nome_fantasia' => 'Barreto Construtora',
                'telefone' => '1158245507',
                'email' => 'laylson2019@icloud.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'BERTOLO ENGENHARIA DE AVALIACOES E PERICIAS EIRELI',
                'cnpj' => '27893249000120',
                'nome_fantasia' => 'BERTOLO ENGENHARIA',
                'telefone' => '1143625402',
                'email' => 'shirley_lupos@hotmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'Brunno André Pereira de Santana',
                'cnpj' => '59616663879',
                'nome_fantasia' => null,
                'telefone' => '',
                'email' => 'x@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'BRZ EMPREENDIMENTOS PORTAL ENCANTOS DE VENEZA SPE LTDA',
                'cnpj' => '51861822000106',
                'nome_fantasia' => 'BRZ EMPREENDIMENTOS PORTAL ENCANTOS DE VENEZA SPE LTDA',
                'telefone' => '3125378787',
                'email' => 'fiscal@brz.eng.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'BYE CUPIM DESCUPINIZACAO E DEDETIZADORA LTDA',
                'cnpj' => '00410785000170',
                'nome_fantasia' => null,
                'telefone' => '1134797988',
                'email' => 'fiscal@rightcontabil.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'BYE CUPINS - DESCUPINIZACAO E DEDETIZADORA LTDA',
                'cnpj' => '45155473000104',
                'nome_fantasia' => null,
                'telefone' => '1135395741',
                'email' => 'simetrocontabil@yahoo.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'C T DA SILVA SERVICOS E PINTURA LTDA',
                'cnpj' => '44416235000134',
                'nome_fantasia' => 'TAVARES SOUZA PINTURAS',
                'telefone' => '1133335194',
                'email' => 'spconsergy@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'CAMPINAS AEROPORTO HOTEL LTDA',
                'cnpj' => '21600348000270',
                'nome_fantasia' => 'Ramada Airport Viracopos Hotel',
                'telefone' => '19989194432',
                'email' => 'rh.rhvc@ahi.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'CASA FRANCESA COMERCIO DE GESSO LTDA',
                'cnpj' => '01425278000173',
                'nome_fantasia' => 'Casa Francesa',
                'telefone' => '1130223424',
                'email' => 'denisconstantino1710@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'CASTILHO PERFURACOES E SEGURANCA DO TRABALHO LTDA',
                'cnpj' => '17310394000187',
                'nome_fantasia' => 'CASTILHO PARCEIRO',
                'telefone' => '11971970604',
                'email' => 'castilho.consultoriasst@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'CETESB COMPANHIA AMBIENTAL DO ESTADO DE SAO PAULO',
                'cnpj' => '43776491000170',
                'nome_fantasia' => null,
                'telefone' => '',
                'email' => 'contato@fgeseg.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'CLAUDIOMAR UCHOA GARCIA',
                'cnpj' => '61562166000196',
                'nome_fantasia' => 'CLAUDIOMAR UCHOA GARCIA',
                'telefone' => '1149988409',
                'email' => 'uchoaclaudio78@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'CMF ENGENHARIA E INSTALACOES LTDA',
                'cnpj' => '49060382000138',
                'nome_fantasia' => 'Cmf Engenharia e Instalacoes',
                'telefone' => '1145803286',
                'email' => 'cicero@cmfinstalacoes.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'CNRP ARQUITETURA E CONSTRUCOES LTDA',
                'cnpj' => '22121094000190',
                'nome_fantasia' => 'RB ARQUITETOS',
                'telefone' => '1191316601',
                'email' => 'x@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'CONSTRUTORA CONCRETIZA LTDA',
                'cnpj' => '69718567000102',
                'nome_fantasia' => 'Nova Casa Construcoes',
                'telefone' => '8596771996',
                'email' => 'x@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'CONSTRUTORA MACHADO FREIRE LTDA',
                'cnpj' => '61740098000108',
                'nome_fantasia' => null,
                'telefone' => '11995311413',
                'email' => 'cmf@cmfreire.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'CONTATTE SERVICOS DE ELETRICA E HIDRAULICA LTDA',
                'cnpj' => '62611343000140',
                'nome_fantasia' => 'Contatte Servicos de Eletrica e Hidraulica',
                'telefone' => '1125920777',
                'email' => 'stelamuller.sm@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'CONTINENTAL CONSTRUTORA LTDA',
                'cnpj' => '18303715000189',
                'nome_fantasia' => 'NHF ENGENHARIA',
                'telefone' => '1630496044',
                'email' => 'expressocontinental@hotmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'D & C ENGENHARIA SERVICOS E PLANEJAMENTO LTDA',
                'cnpj' => '57730635000161',
                'nome_fantasia' => null,
                'telefone' => '1935441380',
                'email' => 'contato@conttis.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'D\' SANTOS CONSTRUCOES LTDA',
                'cnpj' => '34428550000128',
                'nome_fantasia' => 'D\' SANTOS CONSTRUCOES',
                'telefone' => '1180187026',
                'email' => 'contatosdsconstrucoes@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'DANIELLE TEREZA DE ARRUDA E SOUZA 31860843859',
                'cnpj' => '19311126000105',
                'nome_fantasia' => 'TEREZA ARRUDA COSTURA CRIATIVA',
                'telefone' => '1184781412',
                'email' => 'daniterezaarruda@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'DANTAS CONSTRUCOES LTDA',
                'cnpj' => '66848367000178',
                'nome_fantasia' => null,
                'telefone' => '',
                'email' => 'dantasempreiteira@outlook.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'DATA REVESTIMENTOS LTDA',
                'cnpj' => '30381072000197',
                'nome_fantasia' => 'DATA IMPRESSOES',
                'telefone' => '1135547472',
                'email' => 'ailton@datapiso.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'DECACON EMPREITEIRA LTDA',
                'cnpj' => '31569199000105',
                'nome_fantasia' => 'DECACON',
                'telefone' => '1153409644',
                'email' => 'deca.con@hotmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'DELMON ENGENHARIA, CONSTRUCOES E AMBIENTAL LTDA',
                'cnpj' => '52186705000149',
                'nome_fantasia' => 'Delmon Engenharia',
                'telefone' => '1161694160',
                'email' => 'delmon.engenharia@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'DESTRO MAGIC EVENTOS E ENTRETENIMENTOS LTDA',
                'cnpj' => '45341065000139',
                'nome_fantasia' => 'DESTRO MAGIC EVENTOS E ENTRETENIMENTOS',
                'telefone' => '1150724509',
                'email' => 'johnny@magic.ag',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'Deusdete Pereira Filho',
                'cnpj' => '28263411890',
                'nome_fantasia' => null,
                'telefone' => '',
                'email' => 'x@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'DIVERTI EVENTOS F&B LTDA',
                'cnpj' => '21005318000135',
                'nome_fantasia' => 'DIVERTI F&B',
                'telefone' => '1150724509',
                'email' => 'ragionierecontabilidade@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'DOM REFRIGERACAO INDUSTRIAL LTDA',
                'cnpj' => '56093030000144',
                'nome_fantasia' => 'Dom Refrigeracao',
                'telefone' => '1168598231',
                'email' => 'marcio._domingues@hotmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'DS SILVEIRA CONSTRUCOES E REFORMAS LTDA',
                'cnpj' => '63115600000115',
                'nome_fantasia' => null,
                'telefone' => '9183714208',
                'email' => 'ds_silveira@outlook.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'E.N. DE OLIVEIRA EMPREITEIRA',
                'cnpj' => '33775153000160',
                'nome_fantasia' => null,
                'telefone' => '11981760478',
                'email' => 'paralegal@dsempresarial.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'EBN ENGENHARIA E ANALISE ESTRUTURAL LTDA',
                'cnpj' => '54943970000150',
                'nome_fantasia' => null,
                'telefone' => '11998531689',
                'email' => 'eng.edipo.esm@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'EDIFICIOS INTELIGENTES SISTEMAS LTDA',
                'cnpj' => '49436541000156',
                'nome_fantasia' => 'Eis Sistemas',
                'telefone' => '1192743936',
                'email' => 'trigo72@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'EDSON BARBOSA DA SILVA 30513338837',
                'cnpj' => '31336741000171',
                'nome_fantasia' => 'EDSON PARCEIRO',
                'telefone' => '11991930235',
                'email' => 'engsilvas@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'EJD SERVICOS DE CONSTRUCAO CIVIL LTDA',
                'cnpj' => '53904260000158',
                'nome_fantasia' => 'Ejd Construcoes',
                'telefone' => '1839030731',
                'email' => 'escritoriogimenez@hotmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ELANE MEIRA PINHEIRO 33889602835',
                'cnpj' => '36532718000176',
                'nome_fantasia' => 'SOLUTIONS TREINAMENTOS',
                'telefone' => '1196702162',
                'email' => 'elanemeirapinheiro@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ELASTOBOR BORRACHAS E PLASTICOS LTDA',
                'cnpj' => '53840542000210',
                'nome_fantasia' => null,
                'telefone' => '',
                'email' => 'comercial@formedseg.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'Elecdri Engenharia',
                'cnpj' => '30038300000120',
                'nome_fantasia' => null,
                'telefone' => '1127616428',
                'email' => 'adriano.manutencao@hotmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'EMPREITEIRA PEREIRA FREITAS DE CONSTRUÇÃO LTDA',
                'cnpj' => '61704931000165',
                'nome_fantasia' => 'Pereira Freitas Construcoes',
                'telefone' => '1135360436',
                'email' => 'pereirafreitasconstrucao@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ENERGY POWER SOLUTIONS & ENGINEERING LTDA',
                'cnpj' => '42813810000107',
                'nome_fantasia' => 'Energy Power Solutions & Engineering',
                'telefone' => '1281470991',
                'email' => 'douglas.furtado@epbrazil.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ENGELIPE OBRAS E MANUTENCAO LTDA.',
                'cnpj' => '10279848000155',
                'nome_fantasia' => null,
                'telefone' => '1129536429',
                'email' => 'fabio@engelipe.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ENSITECH ENGENHARIA LTDA',
                'cnpj' => '55886059000110',
                'nome_fantasia' => 'Ensitech Engenharia',
                'telefone' => '4197880145',
                'email' => 'meucnpj@contabilizei.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'EPAENGE ENGENHARIA LTDA',
                'cnpj' => '42449812000169',
                'nome_fantasia' => 'EPAENGE ENGENHARIA',
                'telefone' => '1189809729',
                'email' => 'edsonpaulinoengenhariacivil@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'EQUIPA ART MEDICAL - PIERCING LTDA',
                'cnpj' => '40917389000159',
                'nome_fantasia' => null,
                'telefone' => '1937136820',
                'email' => 'escont@escont.cnt.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ERIC MARTINS DA SILVA 42862773808',
                'cnpj' => '41759676000140',
                'nome_fantasia' => 'CONSULTORIA MARTINS',
                'telefone' => '1146362451',
                'email' => 'ericmartins207@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ESCAVADORA SANTA CRUZ LTDA',
                'cnpj' => '49618911000176',
                'nome_fantasia' => 'ESCAVADORA SANTA CRUZ',
                'telefone' => '1938712734',
                'email' => 'escavadorasantacruz@terra.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ETC EMPREENDIMENTOS E TECNOLOGIA EM CONSTRUCOES LTDA.',
                'cnpj' => '03193191000143',
                'nome_fantasia' => 'ETC',
                'telefone' => '1133724399',
                'email' => 'alcides@etcterra.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'EVERTON FRANCISCO DE OLIVEIRA 38144274830',
                'cnpj' => '27494377000109',
                'nome_fantasia' => 'Nps Ar Condicionado e Reformas',
                'telefone' => '1932230639',
                'email' => 'cliver.ar@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'Fábio borges de Oliveira',
                'cnpj' => '21655066897',
                'nome_fantasia' => null,
                'telefone' => '',
                'email' => 'fabioborgesdeoliveiraborges@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'FABIO CARVALHO SOCIEDADE INDIVIDUAL DE ADVOCACIA',
                'cnpj' => '10916423000100',
                'nome_fantasia' => null,
                'telefone' => '2199994880',
                'email' => 'intimacoeslegion@abril.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'FELIPPE FUNDACOES E GEOTECNIA LTDA',
                'cnpj' => '48742608000118',
                'nome_fantasia' => 'Felippe Fundacoes e Geotecnia',
                'telefone' => '11997755033',
                'email' => 'contato@felippefundacoes.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'Fernando B',
                'cnpj' => '16149370879',
                'nome_fantasia' => null,
                'telefone' => '',
                'email' => 'comercial1@formedseg.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'FERNANDO GENEROSO RODRIGUES JUNIOR LTDA',
                'cnpj' => '55706999000180',
                'nome_fantasia' => 'Fgeseg',
                'telefone' => '11973901912',
                'email' => 'abertura@contabilizei.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'FORMED MEDICINA E SEGURANCA DO TRABALHO LTDA',
                'cnpj' => '60109627000107',
                'nome_fantasia' => 'FORMED MEDICINA E SEGURANCA DO TRABALHO LTDA',
                'telefone' => '11992283886',
                'email' => 'comercial@formedseg.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'FORSEG EPI EQUIPAMENTOS DE SEGURANCA LTDA',
                'cnpj' => '49996137000137',
                'nome_fantasia' => 'Forseg',
                'telefone' => '1125521609',
                'email' => 'nerici@hotmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'FRANCISCO.M.M DA SILVA CONSTRUCAO E REFORMA',
                'cnpj' => '19954606000194',
                'nome_fantasia' => 'TL LUMA CONSTRUCAO CIVIL',
                'telefone' => '1120151250',
                'email' => 'luma@lumaengenharia.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'FRIDA SERVICOS DE LIMPEZA LTDA',
                'cnpj' => '58618358000162',
                'nome_fantasia' => 'Frida Limpeza',
                'telefone' => '1165629645',
                'email' => 'linslimpeza@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'GALDI CONSTRUCOES LTDA',
                'cnpj' => '57231619000124',
                'nome_fantasia' => 'Construgaldi',
                'telefone' => '1140134002',
                'email' => 'cleziocosta.engcivil@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'GSS SISTEMAS E INSTALACOES LTDA',
                'cnpj' => '39640368000150',
                'nome_fantasia' => 'GSS SISTEMAS',
                'telefone' => '1186572207',
                'email' => 'adm@gsssistemas.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'GVINAH LTDA',
                'cnpj' => '01585358000196',
                'nome_fantasia' => 'Gvinah',
                'telefone' => '4196520597',
                'email' => 'camilla.ribas@carreiraeribasadvogados.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'H BELICO SEGURANCA LTDA',
                'cnpj' => '48287028000188',
                'nome_fantasia' => null,
                'telefone' => '1194969772',
                'email' => 'atendimento@herafacilities.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'H C SERAFIM TRANSPORTES E LOCACOES',
                'cnpj' => '07329606000114',
                'nome_fantasia' => null,
                'telefone' => '1127136250',
                'email' => 'hbrealiza@hbrealiza.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'H. C. G. DE OLIVEIRA',
                'cnpj' => '10688753000195',
                'nome_fantasia' => 'HERNANE PARCEIRO',
                'telefone' => '11974727251',
                'email' => 'hcseg03@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'HEAVY CONSTRUTORA LTDA',
                'cnpj' => '51957450000108',
                'nome_fantasia' => 'Heavy Construtora',
                'telefone' => '1141983152',
                'email' => 'raullcarvalhoo@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'HELCIO LEITE CAVALHEIRO 13810210854',
                'cnpj' => '47118228000144',
                'nome_fantasia' => null,
                'telefone' => '3599454732',
                'email' => 'helcio.gocil@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'HENTHA INSTALACOES ELETRICAS E HIDRAULICAS LTDA',
                'cnpj' => '06120220000135',
                'nome_fantasia' => null,
                'telefone' => '1122937068',
                'email' => 'contabilpassos@uol.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'HERA FACILITIES SOLUCOES LTDA',
                'cnpj' => '44622509000141',
                'nome_fantasia' => 'Hera Facilities',
                'telefone' => '1194969772',
                'email' => 'atendimento@herafacilities.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'HERBI - ENGENHARIA LTDA',
                'cnpj' => '59238030000183',
                'nome_fantasia' => null,
                'telefone' => '1129574244',
                'email' => 'herbi@herbiengenharia.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'HF ASSESSORIA DE MEDICINA E SEGURANCA DO TRABALHO LTDA',
                'cnpj' => '58376561000170',
                'nome_fantasia' => null,
                'telefone' => '1149011301',
                'email' => 'henrique.log93@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'INEED ENGENHARIA E CONSTRUCOES LTDA',
                'cnpj' => '47576499000143',
                'nome_fantasia' => null,
                'telefone' => '1168545551',
                'email' => 'contato@trescont.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'INNOVA PREDIAL ENGENHARIA DIAGNOSTICA LTDA',
                'cnpj' => '57988496000170',
                'nome_fantasia' => 'Innova Predial',
                'telefone' => '1114632054',
                'email' => 'micaelebrandao@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'INSTALL SYSTEM INSTALACOES E PROJETOS LTDA',
                'cnpj' => '46494377000226',
                'nome_fantasia' => 'INSTALL SYSTEM - SP',
                'telefone' => '1195224651',
                'email' => 'alessandra.gaiba@installsystem.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ISOFELIX ISOLAMENTO HIDRAULICO LTDA',
                'cnpj' => '20515231000145',
                'nome_fantasia' => null,
                'telefone' => '1145195265',
                'email' => 'contato@contabilimpacto.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'J E DOMENICA SERVICOS ADMINISTRATIVOS',
                'cnpj' => '60940299000196',
                'nome_fantasia' => null,
                'telefone' => '1932286222',
                'email' => 'contato@ofccontabil.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'J J CONSTRUCOES LTDA',
                'cnpj' => '58304021000180',
                'nome_fantasia' => 'Jn Construcoes',
                'telefone' => '7598877099',
                'email' => 'joconstrucao@hotmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'J R C DE M FRIGIERI',
                'cnpj' => '33468906000194',
                'nome_fantasia' => 'KEEP SOLUCOES EM ENGENHARIA',
                'telefone' => '11970823000',
                'email' => 'ricardofrigieri@live.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'J.R.B. DO NASCIMENTO CONSTRUCAO CIVIL',
                'cnpj' => '14606397000174',
                'nome_fantasia' => 'J.R.B. CONSTRUCOES',
                'telefone' => '1125615309',
                'email' => 'paralegal@dsempresarial.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'JK FACILITIES LTDA',
                'cnpj' => '45689550000106',
                'nome_fantasia' => 'Jk Facilities',
                'telefone' => '1195728741',
                'email' => 'jkfacilities02@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'JOAO JOAQUIM RIBEIRO 05579634862',
                'cnpj' => '40758642000179',
                'nome_fantasia' => null,
                'telefone' => '1187116886',
                'email' => 'dgcontabil@yahoo.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'João Lenon da Silva',
                'cnpj' => '43458614893',
                'nome_fantasia' => null,
                'telefone' => '',
                'email' => 'duo834149@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'José de Arimatéia Bezerra de Oliveira',
                'cnpj' => '72295716420',
                'nome_fantasia' => null,
                'telefone' => '',
                'email' => 'x@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'JOSE F O LIMA CONSTRUCAO CIVIL',
                'cnpj' => '41097210000127',
                'nome_fantasia' => 'JMM CONSTRUCAO CIVIL',
                'telefone' => '1154362088',
                'email' => 'jflima202126@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'JOTA & JOTA SOLUCOES PROFISSIONAIS LTDA',
                'cnpj' => '54211778000179',
                'nome_fantasia' => null,
                'telefone' => '11994677354',
                'email' => 'josue@jjse.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'JR INSTALACOES E MANUTENCOES ELETRICAS',
                'cnpj' => '57321963000104',
                'nome_fantasia' => null,
                'telefone' => '1184991328',
                'email' => 'raulfernandes.871@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'JV ALVES CONSTRUCAO & SERVICOS LTDA',
                'cnpj' => '56107184000148',
                'nome_fantasia' => 'Jv Alves Construcoes',
                'telefone' => '1154410749',
                'email' => 'contabilpatricia@hotmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'KV MAQ MANUNTENCAO MECANICA INDUSTRIAL LTDA',
                'cnpj' => '58111767000178',
                'nome_fantasia' => 'Kv Maq',
                'telefone' => '11981729475',
                'email' => 'nogueira.rsantos@gamil.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'L. DE CARVALHO - ADMINISTRACAO DE OBRAS LTDA',
                'cnpj' => '41771440000120',
                'nome_fantasia' => null,
                'telefone' => '1995552784',
                'email' => 'notafiscalcps@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'L. DE M. BOTELHO SERVICOS DE LIMPEZA',
                'cnpj' => '15166103000101',
                'nome_fantasia' => 'Presteza Servicos',
                'telefone' => '11988766430',
                'email' => 'lzamoner@uol.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'L. G. ORTIZ SERVICOS DE TERRAPLENAGEM',
                'cnpj' => '40455736000179',
                'nome_fantasia' => 'ORTIZ TERRAPLENAGEM',
                'telefone' => '1142743446',
                'email' => 'ortizterraplenagem@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'L2L FORROS DIVISORIAS E REVESTIMENTOS - LTDA',
                'cnpj' => '46475312000152',
                'nome_fantasia' => 'L2l Forros Divisorias e Revestimentos',
                'telefone' => '1193402788',
                'email' => 'cristianeolima2016@hotmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'LE EMPREITEIRA DE ACABAMENTOS LTDA',
                'cnpj' => '51013045000131',
                'nome_fantasia' => 'LE EMPREITEIRA DE ACABAMENTO',
                'telefone' => '1186944303',
                'email' => 'contato@globalonlinecontabilidade.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'LEO CORREA ENGENHARIA E SERVICOS LTDA',
                'cnpj' => '50095989000132',
                'nome_fantasia' => 'Leo Correa Engenharia e Servicos Ltda',
                'telefone' => '1196352130',
                'email' => 'leonardo.santoscorrea@yahoo.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'LEONARDO ORTIZ CARRARO',
                'cnpj' => '52817456000142',
                'nome_fantasia' => null,
                'telefone' => '1175647840',
                'email' => 'leonardoortizcarraro@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'LJ COSNTRUTORA NEW LTDA',
                'cnpj' => '58935185000106',
                'nome_fantasia' => null,
                'telefone' => '1120531338',
                'email' => 'sheila30@yahoo.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'LNN SERVICOS DE ENGENHARIA E CONSULTORIA LTDA',
                'cnpj' => '11159703000183',
                'nome_fantasia' => 'LNN ENGENHARIA',
                'telefone' => '6133284281',
                'email' => 'legal@diskcontabil.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'LOCSEG LOCACAO DE MAQUINAS LTDA',
                'cnpj' => '22669551000185',
                'nome_fantasia' => null,
                'telefone' => '1435225466',
                'email' => 'lmmaquinas@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'LOMA SERRALHERIA LTDA',
                'cnpj' => '61525407000127',
                'nome_fantasia' => 'Loma Serralheria',
                'telefone' => '1151042794',
                'email' => 'megaferserralheria@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'LPS INSTALACOES LTDA',
                'cnpj' => '40159671000114',
                'nome_fantasia' => 'Leandro Reformas e Instalacoes Eletricas',
                'telefone' => '11963225133',
                'email' => 'lps.leandro.eletrica@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'LUIZ GUSTAVO FERREIRA 22966804882',
                'cnpj' => '28670905000198',
                'nome_fantasia' => null,
                'telefone' => '1933263526',
                'email' => 'luizgpro@outlook.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'LUMA CONSTRUÇÃO CIVIL E REFORMA LTDA ME',
                'cnpj' => '38131740000130',
                'nome_fantasia' => 'LUMA CONSTRUCAO',
                'telefone' => '1132051318',
                'email' => 'luma@lumaengenharia.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'LUMA CONSTRUCAO CIVIL LTDA',
                'cnpj' => '23458864000157',
                'nome_fantasia' => 'LUMA CONSTRUCAO CIVIL',
                'telefone' => '1120151250',
                'email' => 'luma@lumaengenharia.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'LUMA PROJETO EDIFICACAO E REFORMA LTDA',
                'cnpj' => '41756711000178',
                'nome_fantasia' => 'LUMA CONSTRUCAO CIVIL',
                'telefone' => '1120151250',
                'email' => 'luma@lumaengenharia.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'M S DOS SANTOS REFORMAS E PINTURAS EM GERAL',
                'cnpj' => '56059623000194',
                'nome_fantasia' => 'Mcs Pinturas',
                'telefone' => '1159578364',
                'email' => 'mc275132@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'M.BRASILEIRO CONSTRUCOES E IMPERMEABILIZACOES LTDA.',
                'cnpj' => '10174657000129',
                'nome_fantasia' => 'M.BRASILEIRO',
                'telefone' => '',
                'email' => 'mbc.imp@mbrasileiro.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'MARABA CONSTRUCOES LTDA',
                'cnpj' => '49436609000105',
                'nome_fantasia' => 'Maraba Construcoes',
                'telefone' => '1596102905',
                'email' => 'erinaldo.marabaconstrucoes@outlook.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'MARCELO JOSE DOS SANTOS DE OLIVEIRA 26430102807',
                'cnpj' => '28446972000123',
                'nome_fantasia' => 'MAVI MANUTENCOES EM GERAL',
                'telefone' => '1932829128',
                'email' => 'ricktab46@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'MARIO ROBERTO BERGAMINI 07666202806',
                'cnpj' => '28418693000156',
                'nome_fantasia' => 'M B - ADMINISTRACAO DE OBRAS',
                'telefone' => '1932761383',
                'email' => 'eng.mariobergamini@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'MAURICIO DA SILVA COELHO 25974239806',
                'cnpj' => '37791277000190',
                'nome_fantasia' => null,
                'telefone' => '1530313394',
                'email' => 'prestes@prestescontabilidade.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'MEGA FORCE EM INSTALACAO ELETRICA LTDA',
                'cnpj' => '52547182000119',
                'nome_fantasia' => 'FORCE',
                'telefone' => '1170512963',
                'email' => 'rubenspalmeiras827@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'MENEGASSO & NUNES CONSTRUCOES LTDA',
                'cnpj' => '53797401000180',
                'nome_fantasia' => 'Construtora Mazzen',
                'telefone' => '1935427859',
                'email' => 'drcontabilfiscal@yahoo.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'MICHEL INSTALACAO DE PORTAS',
                'cnpj' => '53822483000176',
                'nome_fantasia' => null,
                'telefone' => '1146858406',
                'email' => 'michel.theo20@hotmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'MINIMERCADO 2 AMIGOS LTDA',
                'cnpj' => '43467057000108',
                'nome_fantasia' => 'MERCADO 2 AMIGOS',
                'telefone' => '1143354172',
                'email' => 'nfe@contabiluniao.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'MN FERNANDES CONSTRUTORA LTDA',
                'cnpj' => '61572457000165',
                'nome_fantasia' => 'Mn Fernandes Construtora',
                'telefone' => '1120250033',
                'email' => 'robson@contabilidadeapollo.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'MODELO BASE',
                'cnpj' => '00000000000000',
                'nome_fantasia' => 'MODELO BASE',
                'telefone' => '3591465278',
                'email' => 'souzamarcos@outook.pt',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'MONTICH EQUIPAMENTOS LTDA',
                'cnpj' => '58939131000119',
                'nome_fantasia' => null,
                'telefone' => '1134531311',
                'email' => 'adm@montich.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'MV SOLUCOES ARQUITETURA E SERVICOS LTDA',
                'cnpj' => '55227486000197',
                'nome_fantasia' => 'M&v Obras e Limpeza',
                'telefone' => '1141866301',
                'email' => 'joystercontabil@terra.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'N.M ENGENHARIA, ARQUITETURA & CONSTRUTORA LTDA',
                'cnpj' => '59747705000110',
                'nome_fantasia' => 'Nm Engenharia',
                'telefone' => '1183259682',
                'email' => 'naty-enfermagem@hotmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'NATHALIA DOS SANTOS RODRIGUES',
                'cnpj' => '02669281290',
                'nome_fantasia' => null,
                'telefone' => '',
                'email' => 'nathaliaroddrigues@hotmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'NEW INOX COMERCIO E SERVICOS LTDA',
                'cnpj' => '31543660000142',
                'nome_fantasia' => 'NEW INOX TECHNOLOGY',
                'telefone' => '1123119936',
                'email' => 'amr2002@globo.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'NHZ 02 EMPREENDIMENTOS IMOBILIARIOS SPE LTDA',
                'cnpj' => '30037706000199',
                'nome_fantasia' => null,
                'telefone' => '1127963030',
                'email' => 'adm@nhzincorporadora.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'NICOLAS MERZIUS 54993628234',
                'cnpj' => '35995234000109',
                'nome_fantasia' => 'NIMI-STAELLE ESPERANCE MULTI SERVICES',
                'telefone' => '1189254919',
                'email' => 'francoismerziusnicolas@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'NOBRETOOLS FERRAMENTAS PARA CONCRETO LTDA',
                'cnpj' => '16995511000120',
                'nome_fantasia' => 'NOBRETOOLS FERRAMENTAS',
                'telefone' => '11949322060',
                'email' => 'cmcontabil@superig.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'NOVOMARCO ENGENHARIA E CONSTRUCAO LTDA',
                'cnpj' => '44586998000123',
                'nome_fantasia' => null,
                'telefone' => '1133406655',
                'email' => 'juridico@pigatti.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'NUBIA REGINA GOMES LANCHONETE',
                'cnpj' => '19927451000105',
                'nome_fantasia' => 'Restaurante e Lanchonete da Nubia',
                'telefone' => '1143353594',
                'email' => 'engsilvas@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'OLIVEIRA PINTURA E CONSTRUCAO CIVIL LTDA',
                'cnpj' => '57277403000108',
                'nome_fantasia' => 'Oliveira Pintura e Construcao Civil',
                'telefone' => '1147959937',
                'email' => 'oliveira.pintura@uol.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'OPEL INSTALACAO HIDRAULICA E ELETRICA LTDA',
                'cnpj' => '56965869000125',
                'nome_fantasia' => 'Opel Hidraulica & Eletrica',
                'telefone' => '1187827226',
                'email' => 'opelestalacaesopel@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'OZEAS PEREIRA COSTA',
                'cnpj' => '23299320000190',
                'nome_fantasia' => 'OCP GESSO',
                'telefone' => '8897311090',
                'email' => 'ozeascostapereira@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'PEDACINHO MINEIRO LANCHONETE E COMERCIO DE ALIMENTOS LTDA',
                'cnpj' => '44009209000191',
                'nome_fantasia' => 'Pedacinho Mineiro',
                'telefone' => '1199298464',
                'email' => 'contato@exza.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'PEGASUS SERVICOS OPERACIONAIS LTDA',
                'cnpj' => '16980176000197',
                'nome_fantasia' => null,
                'telefone' => '11978701216',
                'email' => 'pegasusoperacional@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'PERFURARE FUROS E CORTES LTDA',
                'cnpj' => '64181308000163',
                'nome_fantasia' => 'PERFURARE FUROS E CORTES LTDA',
                'telefone' => '11976403670',
                'email' => 'comercial@perfurare.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'PEST OFF CONTROLE BIOLOGICO DE VETORES E PRAGAS LTDA',
                'cnpj' => '36232066000154',
                'nome_fantasia' => null,
                'telefone' => '1135395741',
                'email' => 'simetrocontabil@yahoo.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'PILOTTI CONSTRUTORA LTDA',
                'cnpj' => '17490601000122',
                'nome_fantasia' => 'PILOTTI ENGENHARIA',
                'telefone' => '1126805046',
                'email' => 'contato@pilottiengenharia.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'PIO LOCACAO DE EQUIPAMENTOS LTDA',
                'cnpj' => '46928579000158',
                'nome_fantasia' => 'PIO LOCACAO DE EQUIPAMENTOS LTDA',
                'telefone' => '1199999999',
                'email' => 'financeiro@piolocaco.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'PIO TERRAPLENAGEM E LOCACAO DE MAQUINAS LTDA',
                'cnpj' => '03678712000152',
                'nome_fantasia' => null,
                'telefone' => '1158977965',
                'email' => 'pioloc@hotmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'PIRES PINTURA E EDIFICACOES LTDA',
                'cnpj' => '32535248000143',
                'nome_fantasia' => 'PIRES PINTURA E EDIFICACOES',
                'telefone' => '55119911757',
                'email' => 'pirespintura@outlook.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'PISO TECH BRASIL SOLUCAO EM PISOS INDUSTRIAS LTDA',
                'cnpj' => '11462517000119',
                'nome_fantasia' => null,
                'telefone' => '11991368582',
                'email' => 'pisotechbrasil@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'PLAY INSTALACOES ELETRICAS LTDA',
                'cnpj' => '52367438000106',
                'nome_fantasia' => 'PLAY INSTALACOES ELETRICAS',
                'telefone' => '1162778070',
                'email' => 'srcontabilidade@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'PREMIUM PISOS LTDA',
                'cnpj' => '59589902000158',
                'nome_fantasia' => 'Premium Pisos',
                'telefone' => '1191191101',
                'email' => 'douglaswagner1303@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'PRIMAR ENGENHARIA ELETRICA E CONSTRUCOES LTDA',
                'cnpj' => '51001800000168',
                'nome_fantasia' => 'Primar Engenharia & Construcoes',
                'telefone' => '1126597502',
                'email' => 'fiscal@mnlicontabilidade.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'PROPARK ESTACIONAMENTOS LTDA',
                'cnpj' => '10755459000159',
                'nome_fantasia' => null,
                'telefone' => '800',
                'email' => 'bruno.arcoverde@leve.mobi',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'PROTECTO-TEC SISTEMAS DE SEGURANCA LTDA',
                'cnpj' => '03397988000162',
                'nome_fantasia' => 'Protecto',
                'telefone' => '11970229177',
                'email' => 'patricia@protectotec.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'PROTEK BRASIL SEGURANÇA LTDA',
                'cnpj' => '03928431000100',
                'nome_fantasia' => 'Pglobal',
                'telefone' => '1120208499',
                'email' => 'financeiro@p-global.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'QUICK TERCEIRIZACAO DE SERVICOS LTDA',
                'cnpj' => '33346788000141',
                'nome_fantasia' => 'Lmdc',
                'telefone' => '1198508000',
                'email' => 'lu.quicklimp@hotmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'R MAX CONSTRUCOES LTDA',
                'cnpj' => '62946939000109',
                'nome_fantasia' => 'R Max Construcoes',
                'telefone' => '1113712907',
                'email' => 'rmaxconstrucoes@outlook.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'R.F. DA SILVA - INSTALACOES',
                'cnpj' => '22504700000156',
                'nome_fantasia' => 'R G INSTALACOES',
                'telefone' => '1196987660',
                'email' => 'rgifrs@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'RCJ FUNDACOES E CONSTRUCOES LTDA',
                'cnpj' => '54185923000194',
                'nome_fantasia' => 'Rcj Fundacoes',
                'telefone' => '1162820302',
                'email' => 'rcjfundacoes@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'RDACCA CONSULTORIA E TREINAMENTO LTDA',
                'cnpj' => '55380525000191',
                'nome_fantasia' => null,
                'telefone' => '1998888574',
                'email' => 'adv.adrianacano@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'REQUINTE PINTURAS EIRELI',
                'cnpj' => '35086872000107',
                'nome_fantasia' => 'REQUINTE PINTURAS',
                'telefone' => '1134450782',
                'email' => 'mmacesso@terra.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'RESIDENCIAL MUNE VILA CRUZEIRO SPE LTDA',
                'cnpj' => '61843875000140',
                'nome_fantasia' => 'Vila Cruzeiro',
                'telefone' => '1199999999',
                'email' => 'alan@bklcontabil.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'RHF INCORPORADORA LTDA',
                'cnpj' => '13139242000102',
                'nome_fantasia' => 'RHF INCORPORADORA',
                'telefone' => '1150814309',
                'email' => 'atendimento@rhfconstrutora.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'RM TRATAMENTO E POLIMENTO DE PISOS LTDA',
                'cnpj' => '15724787000101',
                'nome_fantasia' => 'Rm Tratamento e Polimento de Pisos',
                'telefone' => '1184356973',
                'email' => 'eduardo@rmpolimento.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'RN PINTURAS E REFORMAS DE PRÉDIOS COMERCIAIS E RESIDENCIAIS EM GERAL LTDA',
                'cnpj' => '44618245000152',
                'nome_fantasia' => 'RN PINTURAS EM GERAL',
                'telefone' => '1165440114',
                'email' => 'nataliarodrigo83@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ROLIM MACHADO MINAS LTDA',
                'cnpj' => '50988208000139',
                'nome_fantasia' => null,
                'telefone' => '8632131148',
                'email' => 'contato@consultcontabil.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ROMILDO PARCEIRO',
                'cnpj' => '13040621807',
                'nome_fantasia' => null,
                'telefone' => '11941194349',
                'email' => 'otenio.romildo@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ROOL CONSTRUTORA E SERVICOS LTDA',
                'cnpj' => '28368072000105',
                'nome_fantasia' => 'Rool Construtora',
                'telefone' => '1123759938',
                'email' => 'rool@roolconstrutora.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'RRS INSTALACOES LTDA',
                'cnpj' => '47095710000106',
                'nome_fantasia' => 'Ribeiro',
                'telefone' => '1183795711',
                'email' => 'alexandre.magal@hotmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'Ruan Zambom',
                'cnpj' => '56588171889',
                'nome_fantasia' => null,
                'telefone' => '',
                'email' => 'x@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'RUBENS LEONARDO MIGUEL 67687695615',
                'cnpj' => '28955610000168',
                'nome_fantasia' => 'RN INFRA SOLUCOES INDUSTRIAIS',
                'telefone' => '11972836008',
                'email' => 'rlemiguel@yahoo.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'Ryan Zambom',
                'cnpj' => '56588257848',
                'nome_fantasia' => null,
                'telefone' => '',
                'email' => 'x@gmai.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'Sebastião Ferreira de Souza',
                'cnpj' => '13665571820',
                'nome_fantasia' => null,
                'telefone' => '',
                'email' => 'x@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'SEEI SOLUCOES EM ELETRICA E INSTALACOES LTDA',
                'cnpj' => '54123719000149',
                'nome_fantasia' => 'Seei Instalacoes',
                'telefone' => '1177678051',
                'email' => 'hericgruppebarros@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'SERGIO RIBEIRO DE SOUSA 34881717871',
                'cnpj' => '32993158000104',
                'nome_fantasia' => 'INSTALACAOS HIDRAULICA',
                'telefone' => '1195925340',
                'email' => 'sergihosousaribeiriosousa@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'SERPEL METALURGICA LTDA.',
                'cnpj' => '72721467000131',
                'nome_fantasia' => 'Serpel Metalurgica Instalacao de Armazenagem',
                'telefone' => '11999642710',
                'email' => 'contato@serpelmetalurgica.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'SHN CONSTRUCOES LTDA',
                'cnpj' => '57731171000108',
                'nome_fantasia' => null,
                'telefone' => '1996209421',
                'email' => 'heidesconstrucoes@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'SM02 - EDIFICIO TTL SPE LTDA',
                'cnpj' => '44380369000142',
                'nome_fantasia' => null,
                'telefone' => '1189551965',
                'email' => 'pedro@somauma.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'SMART CONSTRUCOES E EXECUCOES DE OBRAS LTDA',
                'cnpj' => '60012608000168',
                'nome_fantasia' => null,
                'telefone' => '1147839840',
                'email' => 'columbo@columbo.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'Soceando Construções LTDA',
                'cnpj' => '05999703000199',
                'nome_fantasia' => 'S&S Construções',
                'telefone' => '1938843965',
                'email' => 'aesoceando@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'SOLANGE ROCHA DE LACERDA',
                'cnpj' => '49379637000120',
                'nome_fantasia' => 'Lumini Gestao & Solucoes Administrativas',
                'telefone' => '1172319837',
                'email' => 'solangelacerda30@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'SP ENGE CONSTRUTORA LTDA.',
                'cnpj' => '06117336000115',
                'nome_fantasia' => null,
                'telefone' => '1132514470',
                'email' => 'cotlider@terra.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'STAR REFORMAS E CONSTRUCOES LTDA',
                'cnpj' => '62869149000169',
                'nome_fantasia' => null,
                'telefone' => '1153330780',
                'email' => 'diretoria@starconstrucoes.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'T.I PERFURACOES EM CONCRETO LTDA',
                'cnpj' => '52434517000192',
                'nome_fantasia' => 'T.i Perfuracoes em Concreto',
                'telefone' => '1178220939',
                'email' => 'tiperfuracoes@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'TALITA FIDENCIO MENDONCA JESUS',
                'cnpj' => '38462668000123',
                'nome_fantasia' => 'MAOS A OBRA',
                'telefone' => '1147003829',
                'email' => 'luciana@queirozepaisassessoria.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'TAREFA',
                'cnpj' => '41699049823',
                'nome_fantasia' => null,
                'telefone' => '',
                'email' => 'asfasf@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'TC SERVICOS PINTURAS CONSTRUCOES E COMERCIO LTDA',
                'cnpj' => '53484933000168',
                'nome_fantasia' => null,
                'telefone' => '9885283762',
                'email' => 'thiagolica72@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'TDS INSTALACOES ELETRICAS LTDA',
                'cnpj' => '55523215000189',
                'nome_fantasia' => 'TR TECNOLOGIA E SERVICOS',
                'telefone' => '1175616471',
                'email' => 'telmo2silva@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'TEKA CONSTRUCOES E MONTAGENS LTDA',
                'cnpj' => '24312971000135',
                'nome_fantasia' => 'TEKA CONSTRUCOES E MONTAGENS EIRELI',
                'telefone' => '1136036608',
                'email' => 'tekaconstrucoesemontagens@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'TERRACON MAQUINAS LTDA',
                'cnpj' => '63181971000103',
                'nome_fantasia' => 'Terracon Maquinas',
                'telefone' => '1146396118',
                'email' => 'tadeuresende@uol.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'THIAGO LUIZ GUALDEVI TAVARES',
                'cnpj' => '18927011000187',
                'nome_fantasia' => 'Thl Terraplenagem',
                'telefone' => '1126699437',
                'email' => 'tavareslubrificantes@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'TRACKER7 SOLUCOES EM RASTREAMENTOS LTDA',
                'cnpj' => '50623598000143',
                'nome_fantasia' => 'Tracker7 Solucoes em Rastreamentos',
                'telefone' => '1141849150',
                'email' => 'cristiano@crservcontabil.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'TRIBASE CONSTRUTORA LTDA',
                'cnpj' => '64840465000133',
                'nome_fantasia' => null,
                'telefone' => '11996717254',
                'email' => 'adm@tribase.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'TRILHAR ENGENHARIA E CONSULTORIA EM SEGURANCA DO TRABALHO LTDA',
                'cnpj' => '34279882000198',
                'nome_fantasia' => 'Trilhar Engenharia e Consultoria em Segurancadotrabalho',
                'telefone' => '1182025337',
                'email' => 'contato@trilhareng.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'TRIOTEC INSTALACOES E MANUTENCOES LTDA',
                'cnpj' => '63100470000147',
                'nome_fantasia' => 'Triotec',
                'telefone' => '1195406610',
                'email' => 'paulo_silva1987@yahoo.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'TROVATA ENGENHARIA E CONSTRUCOES LTDA.',
                'cnpj' => '28988828000119',
                'nome_fantasia' => 'TROVATA ENGENHARIA',
                'telefone' => '1150844999',
                'email' => 'joycenp@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'Ualas Alves Pereira',
                'cnpj' => '10175587523',
                'nome_fantasia' => null,
                'telefone' => '',
                'email' => 'x@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'UBALDO SERVICOS TERCEIRIZADOS LTDA',
                'cnpj' => '26024815000102',
                'nome_fantasia' => 'Ubaldo Servicos Terceirizados',
                'telefone' => '1574014913',
                'email' => 'julianoubaldo76@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'Valéria Natalina Andrade Brienza Valio',
                'cnpj' => '11036732894',
                'nome_fantasia' => null,
                'telefone' => '',
                'email' => 'valeriabrienzavalio@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'VERSATIL DESIGN EM GESSO E CIMENTO LTDA',
                'cnpj' => '53282971000138',
                'nome_fantasia' => 'Versatil Design',
                'telefone' => '1136412866',
                'email' => 'nehizis.nunes@ntwcontabilidade.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'VETRIX CONSTRUCOES LTDA',
                'cnpj' => '62521329000155',
                'nome_fantasia' => 'Vetrix Construcoes',
                'telefone' => '1135682702',
                'email' => 'grife@grifedi.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'VGCO VERTICAL GARDEN LTDA',
                'cnpj' => '10778767000108',
                'nome_fantasia' => 'Vertical Garden',
                'telefone' => '1148732188',
                'email' => 'atendimento@vgco.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'VIKEN SOLUCOES LTDA',
                'cnpj' => '62457334000146',
                'nome_fantasia' => 'Viken Solucoes',
                'telefone' => '1181326269',
                'email' => 'kenny_almede@yahoo.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'WAGNER SANTANA DOS SANTOS',
                'cnpj' => '24612548000150',
                'nome_fantasia' => 'WS REVESTIMENTOS',
                'telefone' => '1156667291',
                'email' => 'contato@manancialcontabil.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'Wallace Santos Leandro',
                'cnpj' => '40786037857',
                'nome_fantasia' => null,
                'telefone' => '',
                'email' => 'x@gmail.com',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'WELINGTON SOUZA DE OLIVEIRA SERVICOS ADMINISTRATIVOS LTDA',
                'cnpj' => '61360179000182',
                'nome_fantasia' => null,
                'telefone' => '1932286222',
                'email' => 'contato@ofccontabil.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'WH ENGENHARIA LTDA',
                'cnpj' => '62534060000141',
                'nome_fantasia' => null,
                'telefone' => '1150109379',
                'email' => 'financeiro@whengenharia.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'WILSON XISTO DE MELO',
                'cnpj' => '19336276000173',
                'nome_fantasia' => 'Engetech',
                'telefone' => '3574007733',
                'email' => 'feli@felicontabil.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'WV FERRAMENTAS E MRO LTDA',
                'cnpj' => '25116267000170',
                'nome_fantasia' => null,
                'telefone' => '1139077004',
                'email' => 'contato@ofmcontabilidade.com.br',
                'ativo' => 1,
            ],
            [
                'empresa_id' => 1,
                'razao_social' => 'ZG CUCINE MOVEIS PLANEJADOS E DECORACOES LTDA',
                'cnpj' => '44736420000106',
                'nome_fantasia' => 'ZG CUCINE',
                'telefone' => '1932959777',
                'email' => 'guilherme@pecinileiloes.com.br',
                'ativo' => 1,
            ],
        ];

        foreach ($clientes as $c) {
            DB::table('clientes')->insert($c);
        }
    }
}
